### ISSUE TITLE
utilize the optional offset parameter

### ISSUE THREAD

**Issue by lorenzoz23** [scott-street/moodqueue#76]
so i started realizing that when i select saved songs, i only ever get my 50 most recently saved songs. this makes sense but i just failed to actually understand that this was what was happening and so i went out trying to find a way to get all of a user's saved tracks which is when i discovered the offset parameter. if we use the offset parameter we could make calls to the saved songs endpoint, updating the offset variable until we receive null to get all of a user's saved tracks; filtering through all of a user's saved songs (all of this also goes for top tracks too btw) would greatly increase our app's effectiveness as getting my most recently saved has started to get kind of annoying and predictable.

i think one possible solution to all of this would be to make an initial call when the app first renders to get the limit of the user's offset (i found that mine was around 300). we could make calls to the saved tracks endpoint until we get null back and that would give us the limit of the user's offset. with that offset, we could save it to local storage and use it to vary up the generated tracks for when our users select saved songs. i think this would greatly enhance our app's functionality if we could, say, generate a queue of saved songs with an offset of 250 to get those deep cuts users like me are so desperate for. 

now, that solution is kinda hairy because it most likely require us to loop several hundred times to get the offset (maybe even worst case of thousands) but it would only be a function we call once when the user first logs in. we could even iterate through their saved tracks by the tens or hundreds instead of a loop that just increases the loop variable by 1 each time. this solution would save time but wouldn't get exact results (doing an increase of 100 each time within the loop could get up to 300 of a user's 350 offset limit, so it would still be pretty damn accurate)

**Comment by katebrune** [comment]
i do agree that we need to get more songs so that the queues end up being more accurate & more diverse. i can work on integrating these changes this week for sure.

PROS:  more accurate & diverse queues/playlists
CONS: will take longer to fetch/process, will need to watch out for rate limiting by spotify

questions i have for you after reading what you said: whats the advantage of storing in local storage instead of in the SpotifyContext or something? 

links to stuff:

endpoint we use for ...
**saved tracks**: https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-users-saved-tracks
**top tracks**: https://developer.spotify.com/documentation/web-api/reference/personalization/get-users-top-artists-and-tracks/
**top artists**: https://developer.spotify.com/documentation/web-api/reference/artists/get-artists-top-tracks/
**recommended**: https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/
