### ISSUE TITLE
"a genre" source selection unclickable

### ISSUE THREAD

**Issue by katebrune** [scott-street/moodqueue#77]
![image](https://user-images.githubusercontent.com/31379789/96461683-4a35ee80-11ea-11eb-80ed-18bdbc7aa364.png)

didn't notice this before merging in the last PR, but just noticed that on https://moodqueue-stage.herokuapp.com/ , the "a genre" selection is unclickable now

edit: just realized it clicks when you make a genre selection, we should talk about this sometime, i feel like if theres a checkbox is implies that it's checkable,  radio buttons are the ones that are usually used as visual indicators that select themselves instead of manual clicking

**Comment by lorenzoz23** [comment]
so, i get where you're coming from with wanting it to be checkable at the start without a genre selected but that leads to some unexpected buggy behavior. the user shouldn't be able to proceed and submit the form without a genre selected but is able to if the checkbox is allowed to be checked from the start. i thought about disabling the checkbox but that would also disable its label and the user needs that to be able to select a genre. 

i'll try and think of a different approach to this problem soon (maybe open the select when checkbox is clicked) to make it so that the checkbox is still always checkable but requires a genre selected to proceed.

**Comment by katebrune** [comment]
i think you could just leave the checkbox as it was before (always checkable/uncheckable) but add a condition to the submit form so that if genre is selected, if the genres value isn't null continue, else if it is (they haven't selected one) don't submit, stay on form, notify error, right ?

**Comment by lorenzoz23** [comment]
yeah, that would work if the genre select value was in the form reducer. if it already is, then i've just been unaware, but if not, then that's just something to add as it should be there.
